name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      METIS_ENV: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Bundle install
      run: |
        gem install bundler -v 2.2.0
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: NPM install
      run: |
        npm install
    - name: Set up database
      env:
        PGHOST: 127.0.0.1
        PGUSER: developer
      run: |
        cp config.yml.test config.yml
        bin/metis create_db
        bin/metis migrate
    - name: Create empty stub folder for Assimilate tests
      run: |
        mkdir -p spec/stubs/blueprints
        mkdir -p spec/data/data_blocks
        mkdir -p spec/data/named
    - name: Create empty data folder for Upload tests
      run: |
        mkdir -p spec/data
    - name: Run test suite
      id: first_test_run
      run: |
        bundle exec rspec spec/
    - name: Run test suite again to detect flaky failures
      if: ${{ steps.first_test_run.outcome == 'success' }}
      id: second_test_run
      run: |
        bundle exec rspec spec/
    - name: Run UI test suite
      if: ${{ steps.second_test_run.outcome == 'success' }}
      run: |
        ./node_modules/.bin/jest
